#%RAML 1.0 NamedExample

value: 
  -
    firstName: "John"
    lastName : "Smith"
    phoneNumber: 9986231790
    email: "Johnsmith@example.com"
    login: "Johnsmith@example.com"
    password: "Johnsmith"
    question: "Who's a major player in the cowboy scene?"
    answer: "Annie Oakley"